service: u-jobs

app: u-jobs
tenant: kwguo

custom:
  dynamodb:
    start:
      migrate: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  stage: dev
  runtime: nodejs8.10
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
        - dynamodb:BatchGetItem
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [figuresTable, Arn]
        - "Fn::GetAtt": [usersTable, Arn]
  environment:
    ENV: ${self:provider.stage}

functions:
  crawl-schedule:
    handler: src/crawl.handler
    timeout: 300
    events:
      - schedule: cron(0 12,18 * * *)
  bot:
    handler: src/server.handler
    events:
      - http:
          method: POST
          path: /

resources:
  Resources:
    figuresTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: figure_bot_figures_${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: figure_bot_users_${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
